matrix:
  include:
    - os: osx
      osx_image: xcode11
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    # Windows currently doesn't support encrypted variables.
    # Once supported uncomment this out & remove build with Docker
    #
    #- os: windows
    #  language: node_js
    #  node_js: "8"

    # - os: linux
    #   services: docker
    #   language: generic

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - ls -a
  - pwd
  - ./osx-add-cert.sh
  - yarn install
  - yarn release
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
